### ISSUE TITLE
Can you explain ??

### ISSUE THREAD

**Issue by yamadaOliva** [emmanuelchucks/drizzle-expo-sqlite#26]
Is the .db file not actually an Expo .db file but exists in a format that users cannot view, right?

**Comment by emmanuelchucks** [comment]
It's a standard sqlite file. It can only be read with database tools.

**Comment by yamadaOliva** [comment]
how can i get .db file. I want to export this to another project

Vào Th 3, 26 thg 3, 2024 vào lúc 20:32 Emmanuel Chucks <
***@***.***> đã viết:

**Comment by emmanuelchucks** [comment]
It is actually created on the user's device. Ignore the empty one in this repo, it does nothing. I'll delete it to avoid confusion.

**Comment by yamadaOliva** [comment]
Thank you !!

Vào Th 4, 27 thg 3, 2024 vào lúc 22:31 Emmanuel Chucks <
***@***.***> đã viết:
